import Head from "next/head";
import React, { Component, useState, useEffect } from "react";
import { render } from "react-dom";
import Message from "../components/Message";
import Image from "next/image";

export default function Home() {
  return (
    <div className="head">
      <Head>
        <title>Dubai Municiplaity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <h1 className="title">
          <a> Dubai Municiplaity</a>
          <Image src="/dmLogo-new.svg" alt="DMLOGO" width={100} height={100} />
        </h1>
        <Message />
      </main>
    </div>
  );
}
